services:
  bot:
    build: .
    container_name: college-schedule-bot
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config.json:/app/config.json
      - ./schedule.json:/app/schedule.json
      - ./changes.json:/app/changes.json
      - ./users.json:/app/users.json
      - ./tools:/app/tools
      - ./messages.json:/app/messages.json
    environment:
      - TZ=Europe/Moscow
